---
- name: Webserver Setup (Nginx, Firewalls, SELinux)
  hosts: nginx
  vars_prompt:
    - name: ansible_password
      prompt: "Enter SSH password"
      private: true
  vars:
    project_root: "/var/www/upms"
    nginx_service: "nginx"

  become: true
  tasks:
    # ---------------------------------------------------------
    # Firewalls, SELinux
    # ---------------------------------------------------------
    - name: Ubuntu/Debian | Allow HTTP/HTTPS in UFW
      community.general.ufw:
        rule: allow
        name: "{{ item }}"
      loop:
        - "Nginx Full"
        - "OpenSSH"
      when: ansible_facts['os_family'] == "Debian"
      ignore_errors: true

    - name: RedHat | Allow HTTP in Firewalld
      ansible.posix.firewalld:
        service: http
        permanent: yes
        state: enabled
      when: ansible_facts['os_family'] == "RedHat"
      ignore_errors: true
      notify: Reload Firewalld

    - name: RedHat | Set SELinux to permissive to allow Nginx access
      ansible.posix.selinux:
        state: permissive
        policy: targeted
      when: ansible_facts['os_family'] == "RedHat"
      ignore_errors: true

    - name: RedHat | Check if SELinux config exists
      ansible.builtin.stat:
        path: /etc/selinux/config
      register: selinux_config_file
      when: ansible_facts['os_family'] == "RedHat"

    - name: RedHat | Persist SELinux permissive state
      ansible.builtin.replace:
        path: /etc/selinux/config
        regexp: '^SELINUX=.*'
        replace: 'SELINUX=permissive'
      when: ansible_facts['os_family'] == "RedHat" and selinux_config_file.stat.exists
      ignore_errors: true

    # ---------------------------------------------------------
    # Nginx Configuration
    # ---------------------------------------------------------
    - name: Configure Nginx Virtual Host
      ansible.builtin.template:
        src: ../templates/nginx.conf.j2
        dest: "/etc/nginx/conf.d/upms.conf"
      notify: Restart Nginx

    - name: Remove default Nginx site (Debian/Ubuntu)
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      when: ansible_facts['os_family'] == "Debian"
      notify: Restart Nginx

    - name: Ensure Nginx is enabled and started
      ansible.builtin.service:
        name: "{{ nginx_service }}"
        state: started
        enabled: true

  handlers:
    - name: Restart Nginx
      ansible.builtin.service:
        name: "{{ nginx_service }}"
        state: restarted

    - name: Reload Firewalld
      ansible.builtin.service:
        name: firewalld
        state: reloaded
      ignore_errors: true
